# You need the AZURE_WEB_APP_NAME and to download the deployment profile and
# add it as a secret to this repo with the name AZURE_WEBAPP_PUBLISH_PROFILE
name: Docker Image CLI

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo. Remove comments to enable
  push:
    branches: [ main ]

  # Allow mannually trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
          
      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: mariam13khan/azure-deploy-template
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    
      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
        
      - name: Configure container and registry settings
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az webapp config container set --docker-custom-image-name ghcr.io/${{ env.REPO }}:${{ github.sha }} --docker-registry-server-password ${{ secrets.DOCKER_HUB_PASSWORD }} --docker-registry-server-user ${{ secrets.DOCKER_HUB_USERNAME }} --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ env.AZURE_GROUP_NAME }}
            az webapp config appsettings set -g ${{ env.AZURE_GROUP_NAME }} -n ${{ env.AZURE_WEBAPP_NAME }} --settings WEBSITES_PORT=8000
